
name: m2-actions-test

on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    name: 'm2 tests & build'      
    steps:
    - uses: actions/checkout@v2
    - name: 'install fresh magento repo'
      if: ${{true}}
      uses: MAD-I-T/magento-actions@master
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'create-project'
        magento_version: 2.4.3
        no_push: 1

